/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHermesBotEventsRouteImport } from './routes/api/hermes.bot.events'
import { Route as ApiHermesBotMessagesRouteImport } from './routes/api/hermes.bot.messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesBotEventsRoute = ApiHermesBotEventsRouteImport.update({
  id: '/api/hermes/bot/events',
  path: '/api/hermes/bot/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesBotMessagesRoute = ApiHermesBotMessagesRouteImport.update({
  id: '/api/hermes/bot/messages',
  path: '/api/hermes/bot/messages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/hermes/bot/events': typeof ApiHermesBotEventsRoute
  '/api/hermes/bot/messages': typeof ApiHermesBotMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/hermes/bot/events': typeof ApiHermesBotEventsRoute
  '/api/hermes/bot/messages': typeof ApiHermesBotMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/hermes/bot/events': typeof ApiHermesBotEventsRoute
  '/api/hermes/bot/messages': typeof ApiHermesBotMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/hermes/bot/events' | '/api/hermes/bot/messages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/hermes/bot/events' | '/api/hermes/bot/messages'
  id: '__root__' | '/' | '/api/hermes/bot/events' | '/api/hermes/bot/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHermesBotEventsRoute: typeof ApiHermesBotEventsRoute
  ApiHermesBotMessagesRoute: typeof ApiHermesBotMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/bot/events': {
      id: '/api/hermes/bot/events'
      path: '/api/hermes/bot/events'
      fullPath: '/api/hermes/bot/events'
      preLoaderRoute: typeof ApiHermesBotEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes/bot/messages': {
      id: '/api/hermes/bot/messages'
      path: '/api/hermes/bot/messages'
      fullPath: '/api/hermes/bot/messages'
      preLoaderRoute: typeof ApiHermesBotMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHermesBotEventsRoute: ApiHermesBotEventsRoute,
  ApiHermesBotMessagesRoute: ApiHermesBotMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
